module.exports = {
  apps: [
    {
      name: 'fems-gateway',
      cwd: './api-gateway',
      script: 'server.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      error_file: '../logs/gateway-error.log',
      out_file: '../logs/gateway-out.log',
    },
    {
      name: 'fems-users',
      cwd: './user-service',
      script: 'server.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      error_file: '../logs/users-error.log',
      out_file: '../logs/users-out.log',
    },
    {
      name: 'fems-extinguishers',
      cwd: './extinguisher-service',
      script: 'server.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      error_file: '../logs/extinguishers-error.log',
      out_file: '../logs/extinguishers-out.log',
    },
    {
      name: 'fems-reports',
      cwd: './reporting-service',
      script: 'server.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      error_file: '../logs/reports-error.log',
      out_file: '../logs/reports-out.log',
    },
    {
      name: 'fems-notifications',
      cwd: './notification-service',
      script: 'server.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      error_file: '../logs/notifications-error.log',
      out_file: '../logs/notifications-out.log',
    },
  ],
};
